# Generated by Django 5.1.6 on 2025-02-20 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='books',
        ),
        migrations.AlterField(
            model_name='librarian',
            name='library',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='librarian', to='relationship_app.library'),
        ),
    ]
